addon/i3dio/__init__.py

All development on the addon will be using blender 2.90 from now on. Backwards compatability with 2.83 is not guaranteed.
BREAKING CHANGE: The version number has been changed. Please upgrade your blender to 2.90

feat(blender): Bump version to blender 2.90

---

addon/i3dio/node_classes/shape.py

As I ran into #97 I decided to put a PR together. I've decided to treat is a missing material, and assign the default material to it, and include a single warning in the log per mesh.
```
i3dio.node_classes.node.IndexedTriangleSet:populate_from_evaluated_mesh:WARNING: [Cube] triangle(s) found with empty material slot, assigning default material
```

feat: warn and assign default material for empty material slots

---

addon/i3dio/ui/mesh.py
addon/i3dio/ui/object.py

Two new features in FS22 for placables are the occluder and the lodDistance property for nodes.
Since they are not applicable in GE (yet) and can therefor only be added manually, this pull requests adds the Options for both Properties.
Since the exporter is setup to only export values which are changes, the default value for lod_distance should only be exported once an actual value is setup (like `0 100`)

Add property for occluder and lodDistance

---

addon/i3dio/node_classes/material.py

The name of the "Separate RGB" input has changed from `Image` to `Color` in blender 3.3.0.  Also support just using an image named "Glossmap" instead.
This change is protected by a blender version check.
The "old way" that still works - using the newly renamed node "Separate Color", manually re-named to "Glossmap"
An optional "new way" - using just an Image Texture manually re-named to "Glossmap"
I've not delved deeply into 3.3 yet, but other than this, it all *seems* to be working correctly - only re-ran a couple quick exports to see if they appeared the same.  Fwiw, been on 3.2 for a week or two prior to this, no issues found there.

Update material.py for blender 3.3.0

---

addon/i3dio/node_classes/material.py

Settings to export mirrors with mirrorShader.xml applied in the shader:
Base Color (RGB): 0 0 0
Metallic: 1
Roughness: 1
Specular: 1

feat(material): Added support to export mirrors

---

addon/i3dio/exporter.py

Fix on binarize export where os.system() did not ignored whitespace in names, which cause not binarize files where converter was located in blender Foundation file

Fix i3dconverter execution path

---

addon/i3dio/node_classes/material.py
addon/i3dio/node_classes/shape.py
addon/i3dio/utility.py

Fix to support materials export for Blender 4.0 with support for older versions.
Blender 4.0 change in Shader input naming:
Specular -> Specular IOR Level
Emission -> Emission Color
Fix Emissive color export since new blender has by default Emissive color 1 1 1 1. Now is emissive color exported when strength has non zero value

Fix shader node inputs for Blender 4.0

---

addon/i3dio/ui/object.py

Add new renderedInViewports prop, if unchecked, object will not be visible/rendered in Giants Editor viewport

Add new renderedInViewports prop

---

addon/i3dio/i3d.py
addon/i3dio/node_classes/file.py
addon/i3dio/node_classes/node.py
addon/i3dio/ui/object.py

Makes it possible to export referenced i3d files directly from blender.
Just add path to a .i3d asset
it will then be visible in the exported .i3d file.
(Only works on Empties)

Add referenceId export

---

addon/i3dio/node_classes/merge_group.py
addon/i3dio/node_classes/node.py
addon/i3dio/node_classes/skinned_mesh.py

merge_group.py and skinned_mesh.py fix using wrong parameter on inherited class init.
export reference file fix, when function has been executed on bones

Fix parameter name and check for reference file on bones

---

addon/i3dio/node_classes/material.py
addon/i3dio/ui/shader_picker.py

- The shaders will now be automatically loaded in a EnumProperty through the data path set in addon preferences
- This includes a operator that will migrate the old "source" property over to the new "shader" enum property (and preserve all the other shader related data)
- Made it possible to add "material_name" to the load_custom_shader and load_custom_shader_variation operators so it can be called through API without needing to have a active object with a active material to run the operators
Should hopefully fix #179

Changes to how you add shaders in the UI

---

addon/i3dio/node_classes/shape.py

First index and vertex was wrong calculated for 3 and more subsets, because function was returning number of vertices / indexes instead of sum of first + count

fix(mesh): subset indexing

---

addon/i3dio/node_classes/shape.py

Instead of logging for each vertex, it now warn once per mesh instead. Should make the log a lot cleaner.
fixes: #96

fix(shape): warn once per mesh for zero-weighted vertices

---

addon/i3dio/node_classes/skinned_mesh.py

Fixed bone transformation issues in skinned meshes, including location and orientation. Made adjustments to ensure transformations are correctly applied and multiplied.
fix: #213

fix(skinned_mesh): resolve issues with bone transformations

---

addon/i3dio/node_classes/material.py

The Material.blend_method API is deprecated as of Blender 4.2. Updated the exporter to use the new Material.surface_render_method instead.

fix(material): update alpha blending to use surface_render_method

---

addon/i3dio/node_classes/material.py
addon/i3dio/node_classes/shape.py

Removed bpy.app.version checks for Blender versions earlier than 4.2.
The addon have been bumped to version 4.2, so no need to keep these messy lines in the addon imo.

fix(blender): remove redundant version checks for pre-4.2 compatibility

---

addon/i3dio/ui/light.py

In a map a light called "sun" use type "directional" so I think this change make sense.

fix(light): update light type mapping for SUN to directional

---

addon/i3dio/node_classes/shape.py
addon/i3dio/ui/mesh.py

Previously, vertex colors were always exported if a layer was present. This commit adds a new property to explicitly enable or disable vertex color export, providing better control for users. This prevents unwanted meshes from exporting with vertex colors.
Based on #211

feat(shape): add property to control vertex color export for meshes

---

addon/i3dio/ui/mesh.py

Added a `poll` function to the `bounding_volume_object` property to restrict its selection to mesh objects only. This ensures that only valid objects can be assigned to this property.

fix(mesh): restrict bounding volume object selection to valid mesh objects

---

addon/i3dio/node_classes/material.py
addon/i3dio/ui/shader_picker.py

Replaced `surface_render_method == 'BLENDED'` check with the new `alpha_blending` property in `i3d_attributes`. Restructured material shader panels for (hopefully) improved code readability and future functionality.
Found one limitation (I think) with the new layout panels, all sub panels you make will inherrit value of the "top level" use_property_split. So had to set that to False for now. Even if you add a new use_property_split within the created panels they will still use the top-level one.
Since @LKAMinco doesn't have that much time these days he asked me to do these changes. (#211)

feat(materials): replace surface_render_method with alpha blending property and restructure panels

---

addon/i3dio/ui/object.py

- Changed LOD distance from StringProperty to FloatVectorProperty for better usability and accuracy.
- Added migration logic to convert old LOD distance values and preserve existing data.
- Implemented validation rules:
- First LOD distance value is always 0 and cannot be changed.
- Subsequent values cannot be smaller than the previous ones.
- Improved UI for managing LOD distances in the object attributes panel:
- Level 0 is always disabled.
- Levels 1-3 are conditionally enabled based on the number of child objects.

feat(lod): migrate LOD distance to FloatVectorProperty

---

addon/i3dio/exporter.py

Fixes an issue where nested armatures in a deep hierarchy were incorrectly flagged
as missing from the export due to only checking against root objects. The export
function now pre-runs through the entire hierarchy to include all nested objects
for accurate checks.
Additionally, corrects a bug introduced by the original commit 3bbf4dc where a new argument
was added before the existing parent argument. This caused functions calling
`_add_object_to_i3d` to pass the wrong values, leading to children being incorrectly
placed at the root level.
Pre-traversing the hierarchy seems to have now performance impact on export time

fix(exporter): resolve incorrect warnings for nested armatures and argument misplacement

---

addon/i3dio/ui/addon_preferences.py

After Blender 4.2, the `online_access` property was introduced as part of the extensions feature to prevent unwanted online activity without user consent. This change ensures compliance with Blender's guidelines for handling online access.
https://docs.blender.org/manual/en/latest/advanced/extensions/addons.html#internet-access

fix(binarize): check online access before invoking I3D converter download

---

addon/i3dio/ui/light.py

Replaced context.object checks with context.light to simplify and clarify the logic.
Light props will now also work with light data UI pinning (like the rest of the light props).

refactor(light): access light directly with context.light

---

addon/i3dio/ui/mesh.py

Use blender 4.1 layout.panel to move bounding volume class directly into main panel.
Additionally access mesh directly with context.mesh (this will also allow the props to be pinned in the data properties menu, like the rest of the props)

refactor(mesh): restructure mesh UI

---

addon/i3dio/node_classes/node.py
addon/i3dio/ui/object.py

This is part of the messy #225 
If anyone have any better idea on where the props/panels should be placed, let me know 🙈
- Removed all "extra" panel classes and replaced with UIlayout.panel instead
- Updated some property descriptions
- Changed i3d_reference_path to i3d_reference_data (PointerProp) to prepear for what will come with FS25 props
- Replaced split type enum presets with a menu instead and made it similar to a preset menu in the header
<table>
<tr>
<td><strong>New object UI with Mesh:</strong></td>
<td><strong>New object UI with Empty:</strong></td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/f4b98933-60fd-4451-903a-d68c915dab48" width="200"></td>
<td><img src="https://github.com/user-attachments/assets/88df2de6-93b3-4efb-b8fe-e1969968bf15" …

refactor(object): restructure object UI

---

addon/i3dio/ui/mesh.py
addon/i3dio/ui/object.py

Corrected a merge conflict where 'rendered in viewports' was left in the object properties but was no longer functional. The property is now properly added to the mesh attributes and displayed in the mesh UI.

fix(attributes): resolve merge issue by moving 'rendered in viewports' property to mesh UI

---

addon/i3dio/ui/object.py

Seems like it was never added to the UI by the looks of it

fix(attributes): add 'object_mask' property to object attributes panel

---

addon/i3dio/exporter.py

Is there a reason this wasn't added?

fix(exporter): implement unused keep_collections_as_transformgroups property

---

addon/i3dio/exporter.py
addon/i3dio/i3d.py
addon/i3dio/node_classes/material.py
addon/i3dio/node_classes/skinned_mesh.py

Make it possible for bones in armatures to set a custom parent
based on the 'Child Of' constraint target (PoseBone). Simplifies
the workflow by allowing a single armature to manage
all bones, instead of requiring one armature per bone.
[childOfConstraint.zip](https://github.com/user-attachments/files/18413527/childOfConstraint.zip)

feat(skinned-mesh): add support for 'Child Of' constraint on bones

---

addon/i3dio/ui/mesh.py

Instead of going into a enum list to select on or off, it both looks better and is faster to select what you want when the cpu mesh enum property use the expand option.
Before:
After:

fix(mesh): use expand option for cpu_mesh property

---

addon/i3dio/i3d.py
addon/i3dio/node_classes/merge_group.py
addon/i3dio/node_classes/shape.py
addon/i3dio/node_classes/skinned_mesh.py

- Fixed an exporter error caused by an extra, unused material slot (with assigned material).
- Fixed a crash when self.i3d.add_material encountered an empty material slot.
- Centralized material handling in populate_from_evaluated_mesh, ensuring all material-related issues are handled in one place.
Tested this change with various blend files, with and without textures, with merge groups, skinned meshes etc etc.
I noticed this randomly because I had accidentally added a extra material to my mesh and that material was not assigned to any triangles. Which then caused a error in the last debug logging inside process_subset function. I then also noticed that original code in ShapeNode populate_xml_element would also add these unused materials + even try to add empty material slots to …

fix(shape): handle empty and unused material slots in IndexedTriangleSet

---

addon/i3dio/exporter.py
addon/i3dio/i3d.py
addon/i3dio/node_classes/merge_children.py
addon/i3dio/node_classes/node.py
addon/i3dio/node_classes/shape.py
addon/i3dio/ui/exporter.py
addon/i3dio/ui/object.py

Safe for FS22
This PR introduces support for merged children export in Blender. The new functionality allows users to merge all child meshes of a specified root object (empty object type) into a single mesh. This feature is designed to work with shaders in Farming Simulator that require normalized generic values.
- **Merge Child Meshes**: Merges all child meshes of a specified root empty object into a single mesh.
- **Unique Normalized Generic Values**: Assigns a unique normalized `generic_value` to each top-level child and its descendants. This is crucial for shaders in Farming Simulator that require normalized generic values.
- **Transform Handling**: Option to apply local transforms to the root’s transform or preserve each mesh's local transform.
- **Interpolation Steps**: Supports …

feat(merge-children): add support for merge children export

---

addon/i3dio/node_classes/skinned_mesh.py
addon/i3dio/ui/exporter.py
addon/i3dio/ui/object.py

- Moved the "Collapse Armature" property from the export panel to individual armature objects.
- Allows per-armature control instead of a global setting.
- Improves flexibility for exporting different armature configurations.

feat(skinned-mesh): move collapse armature property to object level

---

addon/i3dio/i3d.py
addon/i3dio/node_classes/merge_children.py
addon/i3dio/node_classes/shape.py

Due to recent change in how materials were handled the merge children shapes did not end up with any materials, which will crash GE.
A very simple fix which works for FS22 version is to just append materials for merge children shape inside populate_xml_element

fix(merge-children): materials was not added to the shape

---

addon/i3dio/node_classes/material.py

- BSDF node lookup now uses `bl_idname` instead of name, preventing failures when Blender is set to a non-English language.
- Added support for extracting `bumpDepth` from the Normal Map node.
- Introduced a new function to find nodes by name or label, improving Glossmap detection.

fix(material): improve node lookup, bumpDepth support, and export logic

---

addon/i3dio/node_classes/material.py

There was a problem introduced in #281 which caused e.g. normal map default socket value to overwrite diffuseColor.

fix(material): ensure diffuse color is written only for Texture key

---

addon/i3dio/xml_i3d.py

After testing #259 (PR), some shader files failed to parse correctly due to an XML comment at the top level of the file. Removing CommentedTreeBuilder solves this issue. Since we no longer use it to modify XML files, it can be safely removed.

fix(xml): remove unnecessary CommentedTreeBuilder

---

addon/i3dio/exporter.py
addon/i3dio/i3d.py
addon/i3dio/node_classes/merge_children.py
addon/i3dio/node_classes/node.py
addon/i3dio/node_classes/shape.py
addon/i3dio/ui/object.py

Now it uses the merge children root object for the entire logic, all object & mesh attributes is now taken directly from the root instead of copying them from first mesh child.

fix(merge-children): Use mesh object as root instead of empty for better UX and export flow

---

addon/i3dio/node_classes/shape.py

Meshes can contain triangles with invalid or out of range material indices, stored in the 'material_index' attribute. The reason this happen in first place I am unsure about 😅 Potentially something could have been broken when jumping between blender versions, importing corrupted geometry or what ever.... This PR will at least handle such cases by assigning either the only valid material (if only one exist in the mesh) or falling back to the default material.
Also improves handling of empty material slots (`None`). If a triangle references such a slot, the same fallback logic is applied: use the only valid material if available, otherwise fall back to the default.

fix(shape): handle invalid material indices and empty slots with better fallback logic

---

addon/i3dio/ui/object.py

Previously, the property label in the panel header was directly tied to the property itself, causing the entire header (except for the arrow) to toggle the boolean instead of opening/closing the panel.
Now, the label is split out using `header.label`, so the boolean property is only toggleable inside its own box. The rest of the header (except the property box) can now be used to open/close the panel as expected.

fix(ui): separate label from property in panel header

---

addon/i3dio/ui/object.py

- Prevent IndexError when objects reference out-of-range merge group indices (e.g. after copying to another scene or blend file)
- Automatically unset invalid merge group index

fix(merge groups): handle invalid group indices after copy/paste
